services:
  web:
    build: .
    ports:
      - 80:80
      - 443:443
    restart: always
    #depends_on:
      #- certbot
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
